# Autogenerated from /localhome/mha157/Enzyme/enzyme/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
def path(p):
    if not p: return ''
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), p)


#config.llvm_src_root = ""
config.llvm_ver = "12"
config.llvm_obj_root = "/local-scratch/localhome/mha157/llvm-project/build"
config.llvm_tools_dir = "/local-scratch/localhome/mha157/llvm-project/build/./bin"
config.llvm_libs_dir = "/local-scratch/localhome/mha157/llvm-project/build/./lib"
config.enzyme_obj_root = "/localhome/mha157/Enzyme/enzyme/build"
config.target_triple = "x86_64-unknown-linux-gnu"

config.llvm_shlib_ext = ".so"

config.targets_to_build = " X86"

## Check the current platform with regex
import re
EAT_ERR_ON_X86 = ' '
if (re.match(r'^x86_64*', 'x86_64-unknown-linux-gnu') == None) :
  EAT_ERR_ON_X86 = '|| echo \"error is eaten\"'

for arch in config.targets_to_build.split():
    config.available_features.add(arch.lower() + '-registered-target')

# Support substitution of the tools and libs dirs with user parameters. This is
# used when we can't determine the tool dir at configuration time.
try:
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_libs_dir = config.llvm_libs_dir % lit_config.params
except KeyError:
    e = sys.exc_info()[1]
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

# excludes: A list of directories to exclude from the testsuite. The 'Inputs'
# subdirectories contain auxiliary inputs for various tests in their parent
# directories.
config.excludes = ['Inputs']

config.substitutions.append(('%shlibext', config.llvm_shlib_ext))
config.substitutions.append(('%lli', config.llvm_tools_dir + "/lli"))
config.substitutions.append(('%opt', config.llvm_tools_dir + "/opt"))
config.substitutions.append(('%llvmver', config.llvm_ver))
config.substitutions.append(('%FileCheck', config.llvm_tools_dir + "/FileCheck"))
config.substitutions.append(('%clang', config.llvm_tools_dir + "/clang"))
config.substitutions.append(('%loadEnzyme', ''
                                 + (" --enable-new-pm=0" if int(config.llvm_ver) >= 13 else "")
                                 + ' -load=/localhome/mha157/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-' + config.llvm_ver + config.llvm_shlib_ext 
                                 + (" --enzyme-attributor=0" if int(config.llvm_ver) >= 13 else "")
                                 ))
config.substitutions.append(('%loadBC', ''
                                 + ' /localhome/mha157/Enzyme/enzyme/build/BCLoad/BCPass-' + config.llvm_ver + config.llvm_shlib_ext
                                 ))
config.substitutions.append(('%BClibdir', '/localhome/mha157/Enzyme/enzyme/bclib/'))
config.substitutions.append(('%loadClangEnzyme', ''
                                 + (" -fno-experimental-new-pass-manager" if int(config.llvm_ver) >= 13 else "")
                                 + ' -Xclang -load -Xclang /localhome/mha157/Enzyme/enzyme/build/Enzyme/ClangEnzyme-' + config.llvm_ver + config.llvm_shlib_ext
                                 ))

# Let the main config do the real work.
lit_config.load_config(config, "/localhome/mha157/Enzyme/enzyme/test/lit.cfg.py")
